In [ ]:
# 1. Flatten a Nested List
def flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result


# 2. Accessing Nested List Elements
def access_nested_element(lst, indices):
    element = lst
    for i in indices:
        element = element[i]
    return element


# 3. Sum of All Elements in a Nested List
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total


# 4. Remove Specific Element from a Nested List
def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result


# 5. Find Maximum Element in a Nested List
def find_max(lst):
    max_value = None
    for item in lst:
        if isinstance(item, list):
            value = find_max(item)
        else:
            value = item

        if max_value is None or value > max_value:
            max_value = value
    return max_value


# 6. Count Occurrences of an Element in a Nested List
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count


# 7. Deep Flatten
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result


# 8. Nested List Average
def average_nested(lst):
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)


# ================================
# TESTING SECTION (COLAB OUTPUT)
# ================================

print(" Flatten:", flatten([[1, 2], [3, 4], [5]]))

print("Access Element:", access_nested_element(
    [[1,2,3],[4,5,6],[7,8,9]], [1,2])
)

print(" Sum Nested:", sum_nested([[1,2],[3,[4,5]],6]))

print(" Remove Element:", remove_element([[1,2],[3,2],[4,5]], 2))

print(" Find Max:", find_max([[1,2],[3,[4,5]],6]))

print(" Count Occurrences:", count_occurrences([[1,2],[2,3],[2,4]], 2))

print(" Deep Flatten:", deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))

print(" Average Nested:", average_nested([[1,2],[3,4],[5,6]]))

 Flatten: [1, 2, 3, 4, 5]
Access Element: 6
 Sum Nested: 21
 Remove Element: [[1], [3], [4, 5]]
 Find Max: 6
 Count Occurrences: 3
 Deep Flatten: [1, 2, 3, 4, 5, 6, 7, 8]
 Average Nested: 3.5


In [ ]:
# Function to get last n elements
def get_last_n(lst, n):
    return lst[-n:]


# Example list
numbers = [1, 2, 3, 4, 5]

# Get last 2 elements
result = get_last_n(numbers, 2)

print("Last 2 elements:", result)

Last 2 elements: [4, 5]


In [ ]:
# Function to reverse list with skipping
def reverse_skip(lst):
    return lst[-2::-2]


# Example
numbers = [1, 2, 3, 4, 5, 6]
result = reverse_skip(numbers)

print(" Reverse Skip Result:", result)

 Reverse Skip Result: [5, 3, 1]


In [ ]:
# Function to remove first and last element
def remove_first_last(lst):
    return lst[1:-1]


# Example
numbers = [1, 2, 3, 4, 5]
result = remove_first_last(numbers)

print("After removing first & last:", result)

After removing first & last: [2, 3, 4]


In [ ]:
def get_first_n(lst, n):
    return lst[:n]

# Example
numbers = [1, 2, 3, 4, 5]
result = get_first_n(numbers, 3)

print(result)

[1, 2, 3]


In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty 2x2 array:")
print(empty_array)

# 2. Initialize an all one array with size 4x2
ones_array = np.ones((4, 2))
print("\n2. Ones array (4x2):")
print(ones_array)

# 3. Return a new array of given shape and type, filled with fill value
full_array = np.full((3, 3), 7)
print("\n3. Full array (3x3 filled with 7):")
print(full_array)

# 4. Return a new array of zeros with same shape and type as a given array
zeros_like_array = np.zeros_like(full_array)
print("\n4. Zeros like array:")
print(zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(full_array)
print("\n5. Ones like array:")
print(ones_like_array)

# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. List converted to NumPy array:")
print(numpy_array)

1. Empty 2x2 array:
[[5.29917824e-315 0.00000000e+000]
 [3.30808557e-033 2.73417940e-052]]

2. Ones array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full array (3x3 filled with 7):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like array:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

5. Ones like array:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

6. List converted to NumPy array:
[1 2 3 4]


In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
print("1. Array from 10 to 49:")
print(arr1)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix from 0 to 8:")
print(arr2)

# 3. Create a 3x3 identity matrix
arr3 = np.eye(3)
print("\n3. 3x3 Identity matrix:")
print(arr3)

# 4. Create a random array of size 30 and find the mean
arr4 = np.random.random(30)
print("\n4. Random array of size 30:")
print(arr4)
print("Mean:", arr4.mean())

# 5. Create a 10x10 array with random values and find min and max
arr5 = np.random.random((10, 10))
print("\n5. 10x10 random array:")
print(arr5)
print("Minimum:", arr5.min())
print("Maximum:", arr5.max())

# 6. Create a zero array of size 10 and replace 5th element with 1
arr6 = np.zeros(10)
arr6[4] = 1
print("\n6. Zero array with 5th element replaced by 1:")
print(arr6)

# 7. Reverse an array
arr7 = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr7[::-1]
print("\n7. Reversed array:")
print(reversed_arr)

# 8. Create a 2D array with 1 on border and 0 inside
arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0
print("\n8. 2D array with border 1 and inside 0:")
print(arr8)

# 9. Create an 8x8 checkerboard matrix
arr9 = np.zeros((8, 8), dtype=int)
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard pattern:")
print(arr9)

1. Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30:
[0.52356798 0.67891019 0.90436802 0.07230761 0.38980074 0.22684968
 0.18196945 0.51607435 0.14874561 0.58158853 0.93636273 0.96869781
 0.26925487 0.50175005 0.69788048 0.72075713 0.45381891 0.6377164
 0.06415162 0.47863705 0.64642019 0.10655082 0.85625846 0.49539749
 0.04204549 0.73278553 0.54836594 0.49902306 0.33859105 0.26460636]
Mean: 0.48277512074952955

5. 10x10 random array:
[[0.53924588 0.41659553 0.58472684 0.45214246 0.82698694 0.78103483
  0.40240774 0.18961992 0.20227216 0.88622028]
 [0.81281293 0.61838617 0.12472622 0.89479617 0.81159911 0.55747231
  0.76474879 0.72941559 0.27871169 0.1597003 ]
 [0.53598168 0.4101149  0.99550323 0.55682271 0.54160993 0.9436321
  0.93302856 0.81335451 

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
print("1. Addition of x and y:")
print(x + y)

# 2. Subtract the two arrays
print("\n2. Subtraction of x and y:")
print(x - y)

# 3. Multiply the array with any integer (example: 2)
print("\n3. Multiply x with 2:")
print(x * 2)

# 4. Square of each element
print("\n4. Square of elements in x:")
print(np.square(x))

# 5. Dot products
print("\n5. Dot Products:")
print("v . w =", np.dot(v, w))
print("x . v =", np.dot(x, v))
print("x . y =")
print(np.dot(x, y))

# 6. Concatenation
print("\n6. Concatenate x and y along rows:")
print(np.concatenate((x, y), axis=0))  # or np.vstack((x, y))

print("\nConcatenate v and w along columns:")
print(np.vstack((v, w)).T)

# 7. Concatenate x and v
print("\n7. Attempt to concatenate x and v:")
try:
    print(np.concatenate((x, v)))
except ValueError as e:
    print("Error:", e)
    print("Explanation: x is a 2D array (2x2) while v is a 1D array, so their dimensions do not match for concatenation.")

1. Addition of x and y:
[[ 6  8]
 [10 13]]

2. Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

3. Multiply x with 2:
[[ 2  4]
 [ 6 10]]

4. Square of elements in x:
[[ 1  4]
 [ 9 25]]

5. Dot Products:
v . w = 219
x . v = [29 77]
x . y =
[[19 22]
 [50 58]]

6. Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
[[ 9 11]
 [10 12]]

7. Attempt to concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is a 2D array (2x2) while v is a 1D array, so their dimensions do not match for concatenation.


In [ ]:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
identity_result = np.dot(A, A_inv)

print("1. A * A^-1:")
print(identity_result)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\n2. AB:")
print(AB)

print("\nBA:")
print(BA)

print("\nAB != BA:", not np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T * A^T
left_side = np.transpose(AB)
right_side = np.dot(np.transpose(B), np.transpose(A))

print("\n3. (AB)^T:")
print(left_side)

print("\nB^T * A^T:")
print(right_side)

print("\nAre they equal:", np.array_equal(left_side, right_side))


# -------------------------------------------------
# Solve Linear Equations using Matrix Inverse Method
# -------------------------------------------------

# Equations:
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

# Matrix representation AX = B
A_matrix = np.array(
    [[2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]]
)

B_matrix = np.array(
    [[-1],
    [-3],
    [9]]
)

# Find inverse of A
A_matrix_inv = np.linalg.inv(A_matrix)

# Solve X = A^-1 * B
X = np.dot(A_matrix_inv, B_matrix)

print("\nSolution of Linear Equations (x, y, z):")
print(X)

1. A * A^-1:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

AB != BA: True

3. (AB)^T:
[[23 51]
 [13 29]]

B^T * A^T:
[[23 51]
 [13 29]]

Are they equal: True

Solution of Linear Equations (x, y, z):
[[ 2.]
 [ 1.]
 [-2.]]


In [ ]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list starting at index 'start'
    and ending at index 'end' (inclusive).

    Parameters:
    lst (list): The original list.
    start (int): Starting index.
    end (int): Ending index (inclusive).

    Returns:
    list: A sublist from start to end (inclusive).

    Raises:
    ValueError: If indices are invalid.
    """
    if start < 0 or end >= len(lst):
        raise ValueError("Start or end index is out of range.")
    if start > end:
        raise ValueError("Start index cannot be greater than end index.")

    return lst[start:end + 1]  # +1 because Python slicing excludes end


def main():
    print("===== Slice a Sublist Program =====")

    try:
        user_input = input("Enter elements separated by spaces: ").strip()

        if not user_input:
            print("Error: Input list cannot be empty.")
            return

        # Convert to list of numbers
        number_list = [float(num) for num in user_input.split()]

        start = int(input("Enter starting index: "))
        end = int(input("Enter ending index: "))

        result = get_sublist(number_list, start, end)

        print(f"\nOriginal List: {number_list}")
        print(f"Sublist from index {start} to {end}: {result}")

    except ValueError as e:
        print(f"Error: {e}")


if __name__ == "__main__":
    main()

===== Slice a Sublist Program =====
Enter elements separated by spaces: 2
Enter starting index: 3
Enter ending index: 1
Error: Start or end index is out of range.


In [ ]:
def extract_every_other(lst):
    """
    Extracts every other element from a list starting from the first element.

    Parameters:
    lst (list): A list of elements.

    Returns:
    list: A new list containing every other element from the original list.
    """
    return lst[::2]


def main():
    print("===== Extract Every Other Element Program =====")

    try:
        user_input = input("Enter elements separated by spaces: ").strip()

        if not user_input:
            print("Error: Input list cannot be empty.")
            return

        # Convert input to list of numbers
        number_list = [float(num) for num in user_input.split()]

        result = extract_every_other(number_list)

        print(f"Original List: {number_list}")
        print(f"Every Other Element: {result}")

    except ValueError:
        print("Error: Please enter only numeric values separated by spaces.")


if __name__ == "__main__":
    main()

===== Extract Every Other Element Program =====
Enter elements separated by spaces: 2
Original List: [2.0]
Every Other Element: [2.0]


In [ ]:

def convert_units(conversion_type, value):
    """
    Converts units based on the selected conversion type.

    Parameters:
    conversion_type (str): The type of conversion to perform.
    value (float): The numeric value to convert.

    Returns:
    tuple: (converted_value, from_unit, to_unit)
    """

    if conversion_type == '1':  # Meters to Feet
        return value * 3.28084, "m", "ft"
    elif conversion_type == '2':  # Feet to Meters
        return value / 3.28084, "ft", "m"
    elif conversion_type == '3':  # Kilograms to Pounds
        return value * 2.20462, "kg", "lbs"
    elif conversion_type == '4':  # Pounds to Kilograms
        return value / 2.20462, "lbs", "kg"
    elif conversion_type == '5':  # Liters to Gallons
        return value * 0.264172, "L", "gal"
    elif conversion_type == '6':  # Gallons to Liters
        return value / 0.264172, "gal", "L"
    else:
        return None


def main():
    print("===== Unit Conversion Program =====")
    print("Select Conversion Type:")
    print("\nLength:")
    print("  1. Meters (m) → Feet (ft)")
    print("  2. Feet (ft) → Meters (m)")
    print("\nWeight:")
    print("  3. Kilograms (kg) → Pounds (lbs)")
    print("  4. Pounds (lbs) → Kilograms (kg)")
    print("\nVolume:")
    print("  5. Liters (L) → Gallons (gal)")
    print("  6. Gallons (gal) → Liters (L)")

    conversion_type = input("\nEnter your choice (1-6): ")

    try:
        value = float(input("Enter the value to convert: "))
        result = convert_units(conversion_type, value)

        if result is not None:
            converted_value, from_unit, to_unit = result
            print(f"\n{value:.4f} {from_unit} = {converted_value:.4f} {to_unit}")
        else:
            print("Error: Unsupported conversion type selected.")

    except ValueError:
        print("Error: Invalid input. Please enter a numeric value.")


if __name__ == "__main__":
    main()

===== Unit Conversion Program =====
Select Conversion Type:

Length:
  1. Meters (m) → Feet (ft)
  2. Feet (ft) → Meters (m)

Weight:
  3. Kilograms (kg) → Pounds (lbs)
  4. Pounds (lbs) → Kilograms (kg)

Volume:
  5. Liters (L) → Gallons (gal)
  6. Gallons (gal) → Liters (L)

Enter your choice (1-6): 1
Enter the value to convert: 3

3.0000 m = 9.8425 ft


In [ ]:

def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)


def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The average of the numbers.
    """
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The maximum number in the list.
    """
    return max(numbers)


def find_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The minimum number in the list.
    """
    return min(numbers)


def main():
    print("===== Mathematical Operations Program =====")
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Enter your choice (1-4): ")

    try:
        user_input = input("Enter numbers separated by spaces: ")
        number_list = [float(num) for num in user_input.split()]

        if len(number_list) == 0:
            print("Error: The list is empty.")
            return

        if choice == '1':
            result = calculate_sum(number_list)
            print(f"Sum = {result}")
        elif choice == '2':
            result = calculate_average(number_list)
            print(f"Average = {result}")
        elif choice == '3':
            result = find_maximum(number_list)
            print(f"Maximum = {result}")
        elif choice == '4':
            result = find_minimum(number_list)
            print(f"Minimum = {result}")
        else:
            print("Error: Invalid operation selected.")

    except ValueError:
        print("Error: Please enter only numeric values separated by spaces.")


if __name__ == "__main__":
    main()

===== Mathematical Operations Program =====
Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 2
Enter numbers separated by spaces: 2
Average = 2.0
